language: node_js
nodejs:
  - 10

script:
  - npm run ci

notifications:
  email:
    recipients:
      - secure: "BUj/jAHUrQvolyab1ptdv9ZJb+dp1kHAG4ebW+A1u83F27280ni/PEu3Xj6lzo0B8LuHhollwHpO2qhG5kXB73yb5GblgouCDlEawmRJUxiQ4bm4B2hUAtInP5oPq1WvftkVpJsu9Q304/RfNG3HruvaNcI9MdQ6YC+oSrT3Ezyg8Sqhe39ZXjgGNiCvQk0NwpMEe62uXIdtIXRaXqUIibeqNu6X/E9KLpem8ckrKxPOacIj0L0H6IOdkVp8plRtV0+tCuj0Bba3U7Tj+/0U3MbsgU5da0j9BtfuGhWwhseu8BmLuAU0z4TAzekfNUfuXGtLHo2WZrAI+RxLcKW1+AW9CiqY7gHrbPA6s/IToO9keeg9N1zqse52nTQI+VuXYRSrqzTrBYDS/Q7lLzwFq4PAl4WIBfh46uvru+0s9V1PnRndwa+ar0kmQm3IKoWTB0x5W4ACshriyIbB2hy7X0CWkZu8Awm4b2mOPOs5Y0ev/cNHd7RhwbgU1KJ78LyjKC0JnXHAAEQHi8SKaoxog1tfwJ52s1PlhRFpyBhYSwAydeJpWDYVEyjcR8PXWGF2FaoqU11HxNsucNpKEYEDZOpM4Ep0h5PgU+odn8WTL5LUCFAneXLbRzKU1BTlgYh0C0hwVz0X9ZxO6qWJwag5NFVeFY48mJkq53p6nfuvnHs="
