language: node_js
nodejs:
- 10

script:
- npm run ci

notifications:
  email:
    recipients:
    - secure: kn1UBjm/w1FSjExuq7L4ScxiyxikuagkW8xcRpigV4M59uW2AR++rwmq0WJIKIBI9EEM4H51Lqz7yijVwGeMc37giNrkBw+d7xmgbm0aP86qlihnpwOMmEU7z1sa3UwvNa/RolqCbF8o+ObYBbxvPPt//AEvX8y44Ft3m647eQQjwAp0AJOuGCv/PqxbCLpUZ9GGenV/GAiz+7aG5WbV0Y2Ajmk6iBe4APCDx75jxhXur5XbBFEJJ3UJiKU0cGCmewFuVBrG8In+skC02l9JIOKcEfnyt3dFhpI01ouOwKYPnOVA40hGd6U1vDakT3YYqARGIjvO24ta7BWpthMv0FmAiHjJZsgraBmLmfu2EPam95YRRRGnq9GtpdfspHhk/FafOBd1H+SdtDV1d0m6cM9I19/0a62qJksUMKt0wySv3aXqLK7q8+HGX2vCyVJCmiR88TKtvz/JA85NZMqrBceUxfKZpRU5EyUF/X4M8KFrL71o231uxzU7V51/h7SAun27IA0PcCkFEzuV/OcHXaOGZ5V57ulUNMCmO7VkuxtzlVADcJTx2YW/lEF1iYgX2RcpSYosdZfHmgqDHgVJe0hE60OwZ3nOJ0/qtQ87qT64mkouW1SLB5PFaNRuweLo178T9z4OMlaAJskh/b7jBkvx7FIXHFo1FsCS6sPXU/4=
